# Generated by Django 5.1.1 on 2024-10-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
